[package]
name = "portal-solutions-ppcd-sys"
version = "0.1.0"
edition = "2024"
license = "CC0-1.0"
description = "C interface to a PowerPC decoder"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.24"
